name:                AtCoder
version:             0.1.0.0
github:              "dragoon8192/AtCoder"
license:             BSD3
author:              "DRAGOON8192"
maintainer:          "dragoon8192@gmail.com"
copyright:           "2021 DRAGOON8192"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dragoon8192/AtCoder#readme>

dependencies:
- base >= 4.7 && < 5

- QuickCheck
- array
- attoparsec
- bytestring
- containers
- deepseq
- extra
- fgl
- hashable
- heaps
- integer-logarithms
- lens
- massiv
- mono-traversable
- mtl
- mutable-containers
- mwc-random
- parallel
- parsec
- primitive
- psqueues
- random
- reflection
- repa
- template-haskell
- text
- tf-random
- transformers
- unboxing-vector
- unordered-containers
- utility-ht
- vector
- vector-algorithms
- vector-th-unbox

library:
  source-dirs: src

executables:
  AtCoder-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AtCoder

tests:
  AtCoder-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AtCoder
